### ISSUE TITLE
Not in npm?

### ISSUE THREAD

**Issue by netpoetica** [scottstanfield/grunt-markdown-to-json#1]
```
$ npm install grunt-m2j --save-dev

npm http GET https://registry.npmjs.org/grunt-m2j
npm http 404 https://registry.npmjs.org/grunt-m2j
npm ERR! 404 'grunt-m2j' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-m2j" "--save-dev"
npm ERR! cwd /Users/krosenberg/Desktop/Projects/bieber-girlfriend
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/krosenberg/Desktop/Projects/bieber-girlfriend/npm-debug.log
npm ERR! not ok code 0
```

**Comment by netpoetica** [comment]
I solved this with

```
npm install grunt-markdown-to-json --save-dev
```

but the docs need to be updated!

**Comment by scottstanfield** [comment]
Thanks Keith! Will do today. 

---

Scott Stanfield
scott@vertigo.com

**Comment by netpoetica** [comment]
Thanks a ton! This is a really cool module - as jekyll grows in popularity you're going to be finding yourself getting a lot more attention on this :-)

**Comment by scottstanfield** [comment]
<blush> It's my first open source module on npm/github, so I'm kinda embarrassed by the bug. Glad you found it useful!

I am very interested in static-site generation, but in Node, not Ruby (so not Jekyll).

If you want to see my latest, check out the static branch of http://github.com/msrd/msrd.io. It's crazy.

On Jun 3, 2013, at 12:01 PM, Keith Rosenberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks a ton! This is a really cool module - as jekyll grows in popularity you're going to be finding yourself getting a lot more attention on this :-)

**Comment by netpoetica** [comment]
@scottstanfield is there a similar static site generator in node? My company uses Jekyll because he have a lot of in-house support from Rubyists, but I use node for everything else (especially Grunt, and all my own projects)

**Comment by scottstanfield** [comment]
Well, I'm kinda making one. And the markdown-to-json was key.

For now, try using Wintersmith 2.0.
http://www.makeitgo.ws/articles/wintersmith2/

I just pushed up some changes to a nice demo of it:
https://github.com/justinjaywang/paperback

**Comment by netpoetica** [comment]
WIll definitely look into it! I also really love the static site generators - I'm probaby just addicated to compiling

**Comment by scottstanfield** [comment]
Man, you have no idea. It's addictive and I'm not sure why. 

try this:

% hub clone msrd/msrd.io
% cd msrd.io
% npm install
% grunt

It should "run" the site in debug mode, and pop up a browser for you to view and interact.

Then try to build a version suitable for release on a static server:

% grunt release

I've been working on it for weeks for a group I belong to…still need another week, so you're getting an early peek. It's not exactly meant for reuse yet.
